/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#define RCC_BASE_ADDR 		0x40023800UL
#define RCC_CFGR_OFFSET 	0x08UL
#define RCC_CFGR 			(RCC_BASE_ADDR + RCC_CFGR_OFFSET)
#define RCC_AHB1ENR_OFFSET 	0x30UL
#define RCC_AHB1ENR 		(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)
#define GPIOA_BASE_ADDR 	0x40020000UL
#define GPIOA_MODER 		GPIOA_BASE_ADDR
#define GPIOA_AFRH_OFFSET 	0x24UL
#define GPIOA_AFRH 			(GPIOA_BASE_ADDR + GPIOA_AFRH_OFFSET)

int main(void)
{
	// Pointer declarations for memory mapped registers
	uint32_t volatile *const pRCC_CFGR    =  (uint32_t*) RCC_CFGR;
	uint32_t volatile *const pRCC_AHB1ENR =  (uint32_t*) RCC_AHB1ENR;
	uint32_t volatile *const pGPIOA_MODER =  (uint32_t*) GPIOA_MODER;
	uint32_t volatile *const pGPIOA_AFRH  =  (uint32_t*) GPIOA_AFRH;

	// Microcontroller output 1 enable (MCO1)
	*pRCC_CFGR &= 	~(3 << 21);
	*pRCC_CFGR |= 	(4 << 24);
	*pRCC_AHB1ENR|= (1 << 0);

	// Enable Alternate Function 0 mode for PA8
	*pGPIOA_MODER &= ~(3 << 16);
	*pGPIOA_MODER |= (2 << 16);
	*pGPIOA_AFRH &= ~(0xF << 0);

    /* Loop forever */
	for(;;);
}
